services:
  gateway-dev:
    hostname: aigateway
    image: caapim/gateway:11.1.1
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/graphman
# EPHEMERAL MODE
      - ./flatGWconfig.json:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/enrolled/bootstrap_config.json
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      SSG_CLUSTER_HOST: "mycompany.host.com"
      SSG_CLUSTER_PASSWORD: "7layer"
      SSG_JVM_HEAP: "4g"
# DEV MODE STARTS HERE
#      SSG_DATABASE_JDBC_URL: "jdbc:mysql://mysql-server:3306/ssg"
#      SSG_DATABASE_USER: "gateway"
#      SSG_DATABASE_PASSWORD: "7layer"
#  mysql-server:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=true
#      - MYSQL_USER=gateway
#      - MYSQL_PASSWORD=7layer
#      - MYSQL_DATABASE=ssg
#    volumes:
#      - ./local/mysqldata:/var/lib/mysql
#    command:
#      - "--character-set-server=utf8mb3"
#      - "--innodb_log_buffer_size=32M"
#      - "--innodb_log_file_size=80M"
#      - "--max_allowed_packet=8M"
#      - "--log-bin-trust-function-creators=1"
#      - "--default-authentication-plugin=mysql_native_password"
# DEV MODE ENDS HERE
secrets:
  license:
    file: ./license.xml
